apiVersion: v1
kind: Service
metadata:
namespace: ns-navid
  name: {{ include "navid.fullname" . }}
  labels:
    {{- include "navid.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "navid.selectorLabels" . | nindent 4 }}
